  name: Upload website
   
  on:
    push:
      branches:
      - main

  jobs:
    deploy:
      runs-on: ubuntu latest
      steps:
       - uses: actions/checkout@master
       - uses: jakejarvis/s3-sync-action@v0.5.1
    with:
      args: --acl public-read --follow-symlinks --delete
    env:  
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: 'us-east-1'


